# Latest versions of NCCL officially supports CUDA 12.x and 13.x
# Reference: https://docs.nvidia.com/deeplearning/nccl/release-notes/rel_2-29-3.html#rel_2-29-3
cuda_compiler_version:
  - "12.9"
  - "13.1"
