conda_forge_output_validation: true
os_version:
  linux_64: cos6
  linux_aarch64: cos7
  linux_ppc64le: cos7
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
github:
  branch_name: main
  tooling_branch_name: main
bot:
  automerge: true
conda_build:
  pkg_format: '2'
azure:
  store_build_artifacts: True
